### ISSUE TITLE
Error appear in lunch

### ISSUE THREAD

**Issue by ValentinLiu15** [DotOS/manifest#33]
When I tried to execute lunch command for Xiaomi Mi 8 device, the error has happening.

There have two .mk file in dir `<DotOS_Repo_Root_Dir>/device` (the error log has shown).

How to fix it?

Command: `lunch dot_dipper-userdebug`

Error Log:
```
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:312:
build/make/core/product_config.mk:163: error: Product "dot_dipper" ambiguous: matches device/xiaomi/dipper/dot_dipper.mk device/xiaomi_dipper/dot_dipper.mk.
15:05:40 dumpvars failed with: exit status 1
Device dipper not found. Attempting to retrieve device repository from DotOS-Devices Github (http://github.com/DotOS-Devices).
Found repository: device_xiaomi_dipper
Checking branch info
Traceback (most recent call last):
  File "vendor/dot/build/tools/roomservice.py", line 352, in <module>
    main()
  File "vendor/dot/build/tools/roomservice.py", line 331, in main
    fallback_branch = detect_revision(repository)
  File "vendor/dot/build/tools/roomservice.py", line 253, in detect_revision
    result = json.loads(urllib.request.urlopen(githubreq).read().decode())
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: rate limit exceeded
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:312:
build/make/core/product_config.mk:163: error: Product "dot_dipper" ambiguous: matches device/xiaomi/dipper/dot_dipper.mk device/xiaomi_dipper/dot_dipper.mk.
15:05:42 dumpvars failed with: exit status 1
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:312:
build/make/core/product_config.mk:163: error: Product "dot_dipper" ambiguous: matches device/xiaomi/dipper/dot_dipper.mk device/xiaomi_dipper/dot_dipper.mk.
15:05:43 dumpvars failed with: exit status 1

** Don't have a product spec for: 'dot_dipper'
** Do you have the right repo manifest?

```

**Comment by RuRuTiaSaMa** [comment]
you must add a local_manifest to sync  your device vendor kernel source
or put them in yourself

**Comment by ValentinLiu15** [comment]
> you must add a local_manifest to sync your device vendor kernel source or put them in yourself

Thanks so much! This issue have be solved.
